export const nutritionFacts = [
  { nutrient: "Calories", amount: "25" },
  { nutrient: "Total Fat", amount: "0 g (0% DV)" },
  { nutrient: "Saturated Fat", amount: "0 g (0% DV)" },
  { nutrient: "Trans Fat", amount: "0 g" },
  { nutrient: "Polyunsaturated Fat", amount: "0 g" },
  { nutrient: "Monounsaturated Fat", amount: "0 g" },
  { nutrient: "Cholesterol", amount: "0 mg (0% DV)" },
  { nutrient: "Sodium", amount: "70 mg (3% DV)" },
  { nutrient: "Total Carbohydrate", amount: "6 g (2% DV)" },
  { nutrient: "Dietary Fiber", amount: "0 g (0% DV)" },
  { nutrient: "Total Sugars", amount: "5 g" },
  { nutrient: "Includes Added Sugars", amount: "0 g (0% DV)" },
  { nutrient: "Protein", amount: "0 g" },
  { nutrient: "Vitamin D", amount: "0 mcg (0% DV)" },
  { nutrient: "Calcium", amount: "40 mg (2% DV)" },
  { nutrient: "Iron", amount: "0 mg (0% DV)" },
  { nutrient: "Potassium", amount: "570 mg (10% DV)" },
];
